import { motion, useReducedMotion } from "framer-motion";
import { CheckCircle2, Lock, Play, X } from "lucide-react";
import { canAccessLesson } from "@/features/student/utils/lessonHelper";
import type { Lesson, TopicWithLessons } from "@/features/student/api/lessonService";

export function LessonDetailsModal({ lesson, topic, childPlan, completed, lang, canStart, onClose, onStart }: { lesson: Lesson; topic: TopicWithLessons; childPlan: "FREE" | "PRO" | "VIP"; completed: boolean; lang: "vi" | "en"; canStart: boolean; onClose: () => void; onStart: () => void }) {
  const reduceMotion = useReducedMotion();
  const allowed = canAccessLesson(lesson, childPlan);
  const isTimeLab = lesson.lessonNumber === 29;
  return <motion.div className="fixed inset-0 z-[110] grid place-items-center p-4" role="dialog" aria-modal="true" aria-labelledby="lesson-modal-title" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
    <button aria-label={lang === "vi" ? "Đóng thông tin bài học" : "Close lesson details"} className="absolute inset-0 cursor-default bg-slate-950/75 backdrop-blur-md" onClick={onClose} />
    <motion.section initial={reduceMotion ? false : { opacity: 0, y: 24, scale: .96 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={reduceMotion ? { opacity: 0 } : { opacity: 0, y: 16, scale: .97 }} transition={{ type: "spring", stiffness: 360, damping: 30 }} className="relative w-full max-w-[520px] overflow-hidden rounded-[30px] border border-slate-200 bg-white shadow-[0_30px_100px_rgba(0,0,0,.45)] dark:border-slate-700 dark:bg-slate-900">
      <div className={`relative overflow-hidden bg-gradient-to-br ${topic.color || "from-sky-500 to-indigo-600"} p-6 text-white sm:p-7`}>
        {isTimeLab && <><img src="/assets/lessons/math2-b29/time-lab-background.png" alt="" className="absolute inset-0 h-full w-full object-cover opacity-35" /><div className="absolute inset-0 bg-gradient-to-r from-indigo-950/80 via-indigo-900/55 to-violet-900/30" /></>}
        <div className="absolute -right-16 -top-20 h-56 w-56 rounded-full bg-white/15 blur-2xl" /><div className="absolute -bottom-20 left-20 h-40 w-40 rounded-full bg-indigo-950/20 blur-2xl" />
        <button onClick={onClose} aria-label={lang === "vi" ? "Đóng" : "Close"} className="absolute right-4 top-4 z-20 grid h-10 w-10 place-items-center rounded-xl border border-white/20 bg-black/15 text-white transition hover:bg-black/30 active:scale-95"><X className="h-5 w-5" /></button>
        <div className="relative flex items-center gap-4 pr-12"><motion.div animate={reduceMotion ? undefined : { y: [0,-5,0], rotate: [0,-2,2,0] }} transition={{ duration: 3, repeat: Infinity }} className="grid h-20 w-20 shrink-0 place-items-center rounded-3xl border border-white/30 bg-white/20 shadow-xl backdrop-blur"><img src="/robot-head.png" alt="Tí Tách" className="h-16 w-16 object-contain drop-shadow-lg" /></motion.div><div className="min-w-0"><span className="inline-flex rounded-full border border-white/25 bg-white/15 px-2.5 py-1 text-[9px] font-black uppercase tracking-[.16em]">{lang === "vi" ? `Chủ đề ${topic.topicNumber}` : `Topic ${topic.topicNumber}`}</span><h2 id="lesson-modal-title" className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">{lang === "vi" ? `Bài ${lesson.lessonNumber}` : `Lesson ${lesson.lessonNumber}`}</h2></div></div>
        <p className="relative mt-5 text-lg font-black leading-snug sm:text-xl">{lesson.title}</p>
      </div>
      <div className="p-6 sm:p-7">
        <div className="flex flex-wrap gap-2"><span className="rounded-xl bg-sky-50 px-3 py-1.5 text-[10px] font-black uppercase tracking-wide text-sky-600 dark:bg-sky-500/10 dark:text-sky-300">{topic.title}</span><span className="rounded-xl bg-violet-50 px-3 py-1.5 text-[10px] font-black uppercase tracking-wide text-violet-600 dark:bg-violet-500/10 dark:text-violet-300">{lang === "vi" ? `Gói ${lesson.requiredPlan}` : `${lesson.requiredPlan} plan`}</span>{isTimeLab && <><span className="rounded-xl bg-cyan-50 px-3 py-1.5 text-[10px] font-black uppercase tracking-wide text-cyan-600 dark:bg-cyan-500/10 dark:text-cyan-300">{lang === "vi" ? "Đồng hồ 3D" : "3D clock"}</span><span className="rounded-xl bg-fuchsia-50 px-3 py-1.5 text-[10px] font-black uppercase tracking-wide text-fuchsia-600 dark:bg-fuchsia-500/10 dark:text-fuchsia-300">AI Tí Tách</span></>}{completed && <span className="inline-flex items-center gap-1 rounded-xl bg-emerald-50 px-3 py-1.5 text-[10px] font-black uppercase tracking-wide text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-300"><CheckCircle2 className="h-3 w-3" />{lang === "vi" ? "Đã hoàn thành" : "Completed"}</span>}</div>
        <div className="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-800/70"><p className="text-[10px] font-black uppercase tracking-[.16em] text-slate-400">{lang === "vi" ? "Mục tiêu bài học" : "Learning objective"}</p><p className="mt-2 text-sm font-semibold leading-relaxed text-slate-600 dark:text-slate-300">{lesson.description || (lang === "vi" ? "Khám phá bài học và hoàn thành thử thách cùng Tí Tách." : "Explore the lesson and complete the challenge with Ti Tach.")}</p></div>
        {!allowed && <div className="mt-4 flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-3.5 dark:border-amber-500/25 dark:bg-amber-500/10"><Lock className="mt-0.5 h-4 w-4 shrink-0 text-amber-500" /><p className="text-xs font-bold leading-relaxed text-amber-700 dark:text-amber-300">{lang === "vi" ? `Bài học này cần gói ${lesson.requiredPlan}. Hãy nhờ phụ huynh nâng cấp để mở khóa.` : `This lesson requires the ${lesson.requiredPlan} plan. Ask a parent to upgrade and unlock it.`}</p></div>}
        <div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row"><button onClick={onClose} className="h-12 rounded-2xl border border-slate-200 px-5 text-sm font-black text-slate-500 transition hover:bg-slate-100 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-800">{lang === "vi" ? "Để sau" : "Maybe later"}</button><button disabled={!canStart} onClick={onStart} className="group relative flex h-12 flex-1 items-center justify-center gap-2 overflow-hidden rounded-2xl bg-gradient-to-r from-sky-500 to-indigo-600 px-5 text-sm font-black text-white shadow-lg shadow-indigo-500/25 transition hover:-translate-y-0.5 hover:shadow-xl disabled:cursor-not-allowed disabled:from-slate-300 disabled:to-slate-400 disabled:shadow-none dark:disabled:from-slate-700 dark:disabled:to-slate-700"><span className="absolute inset-0 -translate-x-full bg-gradient-to-r from-transparent via-white/20 to-transparent transition-transform duration-700 group-hover:translate-x-full" />{!allowed ? <><Lock className="h-4 w-4" />{lang === "vi" ? "Chưa thể truy cập" : "Access locked"}</> : !canStart ? <>{lang === "vi" ? "Sắp ra mắt" : "Coming soon"}</> : <><Play fill="currentColor" className="h-4 w-4" />{completed ? (lang === "vi" ? "Học lại" : "Learn again") : (lang === "vi" ? "Bắt đầu bài học" : "Start lesson")}</>}</button></div>
      </div>
    </motion.section>
  </motion.div>;
}
