import { useState } from "react";
import { Check, Crown, CreditCard, Gift, Rocket, ShieldCheck, Sparkles, Zap } from "lucide-react";
import { AnimatePresence, motion } from "framer-motion";
import { useNavigate } from "react-router-dom";
import { useActiveChild } from "@/features/dashboard/context/activeChild";
import { useLang } from "@/shared/lib/i18n";
import { DashboardCard, DashboardSkeleton, EmptyState, PageHeader } from "../components/DashboardPrimitives";
import { pageMotion } from "../components/dashboardMotion";

const plans = [
  { id: "FREE", name: { vi: "Miễn phí", en: "Free" }, price: 0, tone: "slate", features: { vi: ["10 bài học cơ bản", "Thống kê tổng quan", "1 hồ sơ học sinh"], en: ["10 basic lessons", "Overview statistics", "1 student profile"] } },
  { id: "PRO", name: { vi: "Pro", en: "Pro" }, price: 55000, tone: "blue", features: { vi: ["Toàn bộ bài học tương tác", "Báo cáo tiến độ chi tiết", "Tối đa 3 hồ sơ học sinh"], en: ["All interactive lessons", "Detailed progress reports", "Up to 3 student profiles"] } },
  { id: "VIP", name: { vi: "VIP", en: "VIP" }, price: 89000, tone: "violet", features: { vi: ["Tất cả quyền lợi Pro", "Lộ trình cá nhân hóa", "Hỗ trợ ưu tiên 24/7"], en: ["Everything in Pro", "Personalized learning path", "24/7 priority support"] } },
] as const;

export function SubscriptionPage() {
  const { activeChild, dashboardData, profiles, isLoading, updateChildPlan } = useActiveChild();
  const { lang } = useLang();
  const navigate = useNavigate();
  const [confirmCancel, setConfirmCancel] = useState(false);
  const [cancelling, setCancelling] = useState(false);
  const text = (vi: string, en: string) => lang === "vi" ? vi : en;
  const money = (amount: number) => new Intl.NumberFormat(lang === "vi" ? "vi-VN" : "en-US", { style: "currency", currency: "VND", maximumFractionDigits: 0 }).format(amount);
  if (isLoading) return <DashboardSkeleton />;
  if (!profiles.length) return <EmptyState icon={CreditCard} title={text("Chưa có hồ sơ để gán gói", "No profile to subscribe")} description={text("Thêm hồ sơ học sinh trước khi chọn gói học tập.", "Add a student profile before choosing a learning plan.")} />;
  if (!activeChild || !dashboardData) return <DashboardSkeleton />;
  const billing = dashboardData.billing;
  const currentPlan = activeChild.plan;

  const cancel = async () => {
    setCancelling(true);
    try { await updateChildPlan(activeChild.id, "FREE"); setConfirmCancel(false); } finally { setCancelling(false); }
  };

  return (
    <motion.div {...pageMotion} className="space-y-6">
      <PageHeader eyebrow={text("Gói học tập", "Learning plan")} title={text(`Gói của ${activeChild.name}`, `${activeChild.name}'s plan`)} description={text("Quản lý quyền lợi và chọn gói phù hợp với nhịp học của bé.", "Manage benefits and choose a plan that fits your child's learning pace.")} />
      <section className="relative overflow-hidden rounded-[28px] bg-gradient-to-br from-blue-600 via-indigo-600 to-violet-600 p-6 text-white shadow-xl shadow-indigo-500/15 sm:p-8">
        <div className="absolute -right-16 -top-16 h-64 w-64 rounded-full bg-white/10" /><div className="absolute -bottom-20 left-1/3 h-48 w-48 rounded-full bg-cyan-300/10" />
        <div className="relative flex flex-col gap-6 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-4"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-white/15 backdrop-blur"><Crown className="h-6 w-6 text-amber-300" /></span><div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-100">{text("Đang sử dụng", "Current plan")}</p><h2 className="mt-1 text-3xl font-black">{billing?.planName || currentPlan}</h2><p className="mt-1 text-sm font-medium text-blue-100">{currentPlan === "FREE" ? text("Không tự động gia hạn", "No automatic renewal") : `${text("Gia hạn", "Renews")} ${billing?.renewalDate || "—"}`}</p></div></div><div className="md:text-right"><p className="text-3xl font-black">{currentPlan === "FREE" ? money(0) : money(billing?.pricePerMonth || 0)}</p><p className="text-sm font-semibold text-blue-100">/{text("tháng", "month")}</p><span className="mt-3 inline-flex items-center gap-2 rounded-full bg-emerald-400/20 px-3 py-1 text-xs font-black text-emerald-100"><span className="h-2 w-2 rounded-full bg-emerald-300" />{text("Đang hoạt động", "Active")}</span></div></div>
      </section>

      <div className="grid gap-4 sm:grid-cols-3">
        {[{ icon: ShieldCheck, label: text("Thanh toán an toàn", "Secure payment"), value: billing?.paymentMethod || text("Chưa liên kết", "Not linked") }, { icon: Zap, label: text("Truy cập tức thì", "Instant access"), value: text("Kích hoạt ngay", "Activates instantly") }, { icon: Gift, label: text("Hủy linh hoạt", "Flexible cancellation"), value: text("Không phí ẩn", "No hidden fees") }].map((item) => <DashboardCard key={item.label} className="p-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-blue-50 text-blue-600 dark:bg-blue-500/10 dark:text-blue-300"><item.icon className="h-4 w-4" /></span><span className="min-w-0"><span className="block text-xs font-bold text-slate-400">{item.label}</span><span className="block truncate text-sm font-black text-slate-800 dark:text-white">{item.value}</span></span></div></DashboardCard>)}
      </div>

      <div><div className="mb-4"><p className="text-xs font-black uppercase tracking-[.16em] text-slate-400">{text("So sánh quyền lợi", "Compare benefits")}</p><h2 className="mt-1 text-xl font-black text-slate-900 dark:text-white">{text("Chọn đúng gói, học đúng nhịp", "Choose the right learning pace")}</h2></div><div className="grid gap-4 lg:grid-cols-3">{plans.map((plan, index) => { const selected = currentPlan === plan.id; const highlight = plan.id === "PRO"; return <motion.article key={plan.id} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .06 }} whileHover={{ y: -4 }} className={`relative flex flex-col rounded-[26px] border p-6 ${selected ? "border-blue-500 bg-blue-50/60 ring-2 ring-blue-500/10 dark:bg-blue-500/10" : "border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900/80"}`}>{highlight && !selected && <span className="absolute -top-3 left-6 rounded-full bg-gradient-to-r from-blue-600 to-indigo-600 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-white">{text("Phổ biến", "Popular")}</span>}<div className="flex items-center justify-between"><span className={`grid h-11 w-11 place-items-center rounded-2xl ${plan.id === "VIP" ? "bg-violet-50 text-violet-600 dark:bg-violet-500/10 dark:text-violet-300" : plan.id === "PRO" ? "bg-blue-50 text-blue-600 dark:bg-blue-500/10 dark:text-blue-300" : "bg-slate-100 text-slate-500 dark:bg-slate-800"}`}>{plan.id === "VIP" ? <Crown className="h-5 w-5" /> : plan.id === "PRO" ? <Sparkles className="h-5 w-5" /> : <Rocket className="h-5 w-5" />}</span>{selected && <span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-black text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-300">{text("GÓI HIỆN TẠI", "CURRENT")}</span>}</div><h3 className="mt-5 text-xl font-black text-slate-900 dark:text-white">{plan.name[lang]}</h3><p className="mt-2 text-3xl font-black text-slate-950 dark:text-white">{money(plan.price)}<span className="text-xs font-bold text-slate-400">/{text("tháng", "month")}</span></p><ul className="my-6 flex-1 space-y-3">{plan.features[lang].map((feature) => <li key={feature} className="flex items-start gap-2.5 text-sm font-semibold text-slate-600 dark:text-slate-300"><span className="mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-emerald-50 text-emerald-500 dark:bg-emerald-500/10"><Check className="h-3 w-3" /></span>{feature}</li>)}</ul>{selected ? <button disabled className="w-full rounded-2xl bg-slate-100 px-4 py-3 text-sm font-black text-slate-400 dark:bg-slate-800">{text("Đang sử dụng", "Current plan")}</button> : <button onClick={() => navigate(`/dashboard/payment?plan=${plan.id}`)} className="w-full rounded-2xl bg-slate-900 px-4 py-3 text-sm font-black text-white transition hover:bg-blue-600 dark:bg-white dark:text-slate-950 dark:hover:bg-blue-400">{text("Chọn gói này", "Choose this plan")}</button>}</motion.article>; })}</div></div>
      {currentPlan !== "FREE" && <div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-black text-slate-800 dark:text-white">{text("Bạn muốn dừng gói hiện tại?", "Want to stop the current plan?")}</p><p className="mt-1 text-xs text-slate-400">{text("Bé vẫn dùng quyền lợi đến hết chu kỳ đã thanh toán.", "Benefits remain available until the paid period ends.")}</p></div><button onClick={() => setConfirmCancel(true)} className="text-sm font-black text-rose-500">{text("Hủy đăng ký", "Cancel subscription")}</button></div>}
      <AnimatePresence>{confirmCancel && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/60 p-4 backdrop-blur-sm"><motion.div initial={{ opacity: 0, scale: .94, y: 16 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={{ opacity: 0, scale: .96 }} className="w-full max-w-md rounded-[28px] border border-slate-200 bg-white p-6 shadow-2xl dark:border-slate-700 dark:bg-slate-900"><h2 className="text-xl font-black text-slate-900 dark:text-white">{text("Xác nhận hủy gói?", "Cancel this plan?")}</h2><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{text("Gói sẽ chuyển về Miễn phí và dữ liệu học tập vẫn được giữ nguyên.", "The plan will switch to Free and learning data will remain intact.")}</p><div className="mt-6 flex gap-3"><button onClick={() => setConfirmCancel(false)} className="flex-1 rounded-2xl border border-slate-200 px-4 py-3 text-sm font-black text-slate-600 dark:border-slate-700 dark:text-slate-300">{text("Giữ gói", "Keep plan")}</button><button onClick={cancel} disabled={cancelling} className="flex-1 rounded-2xl bg-rose-500 px-4 py-3 text-sm font-black text-white disabled:opacity-60">{cancelling ? text("Đang xử lý...", "Processing...") : text("Xác nhận hủy", "Confirm cancel")}</button></div></motion.div></motion.div>}</AnimatePresence>
    </motion.div>
  );
}
