import { motion } from "framer-motion";
import { ArrowLeft, BookOpen, CalendarDays, Crown, GraduationCap, Mail, Phone, ShieldCheck, UserRound, Users } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { useAdminParentsQuery } from "@/features/admin/api/adminQueries";
import { AdminPageLoading } from "@/features/admin/components/ui";

export function AdminUserDetailPage({ type }: { type: "parent" | "student" }) {
  const { id } = useParams();
  const { data: parents = [], isPending } = useAdminParentsQuery();
  if (isPending) return <AdminPageLoading title="Đang tải hồ sơ người dùng" description="Đang đồng bộ thông tin tài khoản và tiến độ học tập." metricCount={4} />;
  const parent = type === "parent" ? parents.find((item) => item.id === id) : parents.find((item) => item.children.some((child) => child.id === id));
  const student = type === "student" ? parent?.children.find((item) => item.id === id) : null;
  if (!parent || (type === "student" && !student)) return <Empty />;

  const title = student?.name || parent.name;
  const status = (student?.status || parent.status) === "active" ? "Hoạt động" : (student?.status || parent.status) === "suspended" ? "Bị khóa" : "Không hoạt động";
  return <motion.div initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} className="space-y-5 pb-8">
    <Link to="/admin/users" className="inline-flex items-center gap-2 text-sm font-bold text-muted-foreground transition hover:text-indigo-500"><ArrowLeft className="h-4 w-4" />Quay lại danh sách</Link>
    <section className="overflow-hidden rounded-[28px] border border-indigo-400/20 bg-gradient-to-br from-slate-950 via-indigo-950 to-violet-950 p-6 text-white shadow-xl sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><span className="grid h-20 w-20 place-items-center rounded-3xl bg-white/10 text-3xl font-black ring-1 ring-white/15">{student?.avatarEmoji || initials(parent.name)}</span><div className="flex-1"><p className="text-xs font-bold uppercase tracking-[.16em] text-indigo-300">{student ? "Hồ sơ học sinh" : "Hồ sơ phụ huynh"}</p><h2 className="mt-2 text-3xl font-black">{title}</h2><p className="mt-2 text-sm text-slate-300">{student ? `Thuộc gia đình ${parent.name}` : `${parent.children.length} hồ sơ học sinh trực thuộc`}</p></div><span className={`w-fit rounded-full px-3 py-1.5 text-xs font-bold ${status === "Hoạt động" ? "bg-emerald-400/15 text-emerald-300" : "bg-rose-400/15 text-rose-300"}`}>{status}</span></div></section>

    {student ? <StudentDetails student={student} parent={parent} /> : <ParentDetails parent={parent} />}
  </motion.div>;
}

function ParentDetails({ parent }: { parent: ReturnType<typeof useParentShape> }) { return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Info icon={Phone} label="Số điện thoại" value={parent.phone || "Chưa cập nhật"} /><Info icon={Mail} label="Email" value={parent.email || "Chưa cập nhật"} /><Info icon={CalendarDays} label="Ngày đăng ký" value={formatDate(parent.createdAt)} /><Info icon={ShieldCheck} label="Vai trò" value="Phụ huynh" /></section><section className="rounded-[24px] border border-border bg-card p-5 shadow-sm"><div className="flex items-center gap-3"><Users className="h-5 w-5 text-indigo-500" /><div><h3 className="font-extrabold">Học sinh trực thuộc</h3><p className="text-xs text-muted-foreground">{parent.children.length} hồ sơ trong gia đình</p></div></div><div className="mt-5 grid gap-3 lg:grid-cols-2">{parent.children.map((student) => <Link key={student.id} to={`/admin/users/students/${student.id}`} className="flex items-center gap-3 rounded-2xl border border-border p-4 transition hover:border-indigo-500/30 hover:bg-indigo-500/5"><span className="grid h-11 w-11 place-items-center rounded-xl bg-muted text-xl">{student.avatarEmoji}</span><span className="min-w-0 flex-1"><strong className="block truncate">{student.name}</strong><small className="text-muted-foreground">{student.grade} · {student.plan}</small></span></Link>)}</div></section></>; }

function StudentDetails({ student, parent }: { student: ReturnType<typeof useStudentShape>; parent: ReturnType<typeof useParentShape> }) { return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Info icon={GraduationCap} label="Khối lớp" value={student.grade || "Chưa cập nhật"} /><Info icon={Crown} label="Gói học" value={student.plan} /><Info icon={CalendarDays} label="Thời hạn còn lại" value={student.plan === "FREE" ? "Không giới hạn" : `${student.planDaysLeft || 0} ngày`} /><Info icon={BookOpen} label="Bài đã học" value={String(student.totalLessons || 0)} /></section><section className="grid gap-5 lg:grid-cols-2"><div className="rounded-[24px] border border-border bg-card p-5 shadow-sm"><h3 className="font-extrabold">Thông tin hồ sơ</h3><div className="mt-4 grid grid-cols-2 gap-3"><Field label="Giới tính" value={student.gender || "Chưa cập nhật"} /><Field label="Điểm trung bình" value={`${student.avgScore || 0}/100`} /><Field label="Ngày tạo" value={formatDate(student.createdAt)} /><Field label="Hoạt động cuối" value={formatDate(student.lastActive)} /></div></div><div className="rounded-[24px] border border-border bg-card p-5 shadow-sm"><h3 className="font-extrabold">Phụ huynh quản lý</h3><Link to={`/admin/users/parents/${parent.id}`} className="mt-4 flex items-center gap-3 rounded-2xl bg-muted/50 p-4 transition hover:bg-indigo-500/10"><span className="grid h-12 w-12 place-items-center rounded-xl bg-indigo-500 text-sm font-black text-white">{initials(parent.name)}</span><span><strong className="block">{parent.name}</strong><small className="text-muted-foreground">{parent.phone || "Chưa có số điện thoại"}</small></span></Link></div></section></>; }

function Info({ icon: Icon, label, value }: { icon: typeof UserRound; label: string; value: string }) { return <motion.article whileHover={{ y: -3 }} className="rounded-[22px] border border-border bg-card p-5 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-500/10 text-indigo-500"><Icon className="h-4 w-4" /></span><p className="mt-4 text-xs font-bold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 font-extrabold">{value}</p></motion.article>; }
function Field({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-muted/50 p-3"><p className="text-[10px] uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-sm font-bold">{value}</p></div>; }
function Empty() { return <div className="rounded-[24px] border border-border bg-card p-12 text-center"><UserRound className="mx-auto h-8 w-8 text-muted-foreground" /><p className="mt-3 font-bold">Không tìm thấy hồ sơ</p><Link to="/admin/users" className="mt-4 inline-block text-sm font-bold text-indigo-500">Quay lại danh sách</Link></div>; }
function useParentShape() { return {} as NonNullable<ReturnType<typeof useAdminParentsQuery>["data"]>[number]; }
function useStudentShape() { return {} as ReturnType<typeof useParentShape>["children"][number]; }
function initials(name: string) { return name.split(/\s+/).filter(Boolean).map((part) => part[0]).join("").slice(0, 2).toUpperCase() || "PH"; }
function formatDate(value?: string | null) { if (!value) return "Chưa cập nhật"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleDateString("vi-VN"); }
