import { useEffect, useMemo, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { AnimatePresence, motion } from "framer-motion";
import { BookOpen, Edit3, Layers3, Save, X } from "lucide-react";
import * as service from "@/features/admin/api/adminService";
import { adminQueryKeys, useAdminLessonsQuery } from "@/features/admin/api/adminQueries";
import { AdminFilterSelect, AdminPageHero, AdminPageLoading, AdminPagination, AdminSearch } from "@/features/admin/components/ui";

type Plan = "FREE" | "PRO" | "VIP"; type Status = "published" | "draft"; const PAGE_SIZE = 12;
const statusMeta = { published: { label: "Đã hoàn thành", style: "bg-emerald-500/10 text-emerald-500" }, draft: { label: "Chưa hoàn thiện", style: "bg-amber-500/10 text-amber-500" } };
export function AdminLessonsPage() {
  const queryClient = useQueryClient(); const { data: lessons = [], isPending } = useAdminLessonsQuery();
  const [search, setSearch] = useState(""); const [plan, setPlan] = useState<"all" | Plan>("all"); const [status, setStatus] = useState<"all" | Status>("all"); const [topic, setTopic] = useState("all"); const [page, setPage] = useState(1); const [editing, setEditing] = useState<service.AdminLesson | null>(null); const [form, setForm] = useState<Partial<service.AdminLesson>>({}); const [saving, setSaving] = useState(false);
  const topics = useMemo(() => Array.from(new Map(lessons.map((item) => [item.topicId, item.topicName])).entries()).map(([value, label]) => ({ value, label })), [lessons]);
  const filtered = useMemo(() => { const q = search.trim().toLocaleLowerCase("vi"); return lessons.filter((item) => (!q || [item.title, item.topicName, item.gameType].some((value) => String(value || "").toLocaleLowerCase("vi").includes(q))) && (plan === "all" || item.requiredPlan === plan) && (status === "all" || item.status === status) && (topic === "all" || item.topicId === topic)); }, [lessons, search, plan, status, topic]);
  useEffect(() => setPage(1), [search, plan, status, topic]); const rows = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
  function open(item: service.AdminLesson) { setEditing(item); setForm({ title: item.title, description: item.description, requiredPlan: item.requiredPlan, status: item.status, gameType: item.gameType, emoji: item.emoji }); }
  async function save() { if (!editing) return; setSaving(true); try { const updated = await service.updateAdminLesson(editing.id, form); queryClient.setQueryData<service.AdminLesson[]>(adminQueryKeys.lessons, (current = []) => current.map((item) => item.id === editing.id ? { ...item, ...updated } : item)); setEditing(null); } catch (error) { console.error(error); } finally { setSaving(false); } }
  if (isPending) return <AdminPageLoading title="Đang chuẩn bị thư viện bài học" description="Đang đồng bộ nội dung, gói truy cập và trạng thái phát hành." />;
  return <div className="space-y-5 pb-8"><AdminPageHero eyebrow="Content operations" title="Thư viện bài học có tổ chức" description="Tra cứu và cập nhật nội dung học tập theo chủ đề, gói truy cập và trạng thái phát hành." icon={BookOpen} metrics={[{ label: "Bài học", value: lessons.length, icon: BookOpen }, { label: "Chủ đề", value: topics.length, icon: Layers3 }]} />
    <section className="rounded-[22px] border border-border bg-card p-3 shadow-sm"><div className="grid gap-2 xl:grid-cols-[minmax(280px,1fr)_180px_190px_220px]"><AdminSearch value={search} onChange={setSearch} placeholder="Tên bài học, chủ đề hoặc loại game…" /><AdminFilterSelect label="Gói" value={plan} onChange={setPlan} options={[{ value: "all", label: "Tất cả gói" }, { value: "FREE", label: "FREE" }, { value: "PRO", label: "PRO" }, { value: "VIP", label: "VIP" }]} /><AdminFilterSelect label="Trạng thái" value={status} onChange={setStatus} options={[{ value: "all", label: "Tất cả trạng thái" }, { value: "published", label: "Đã hoàn thành" }, { value: "draft", label: "Chưa hoàn thiện" }]} /><AdminFilterSelect label="Chủ đề" value={topic} onChange={setTopic} options={[{ value: "all", label: "Tất cả chủ đề" }, ...topics]} /></div></section>
    <section className="overflow-hidden rounded-[24px] border border-border bg-card shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[920px] text-sm"><thead><tr className="bg-muted/40 text-left text-[11px] font-bold uppercase tracking-[.1em] text-muted-foreground"><th className="px-5 py-3.5">Bài học</th><th className="px-4 py-3.5">Chủ đề</th><th className="px-4 py-3.5">Loại nội dung</th><th className="px-4 py-3.5 text-center">Gói</th><th className="px-4 py-3.5 text-center">Trạng thái</th><th className="px-5 py-3.5 text-right">Thao tác</th></tr></thead><tbody>{rows.map((item, index) => <LessonRow key={item.id} item={item} index={index} onEdit={() => open(item)} />)}</tbody></table>{!rows.length && <div className="py-16 text-center text-sm text-muted-foreground">Không tìm thấy bài học phù hợp.</div>}</div><AdminPagination page={page} pageSize={PAGE_SIZE} total={filtered.length} onChange={setPage} /></section>
    <AnimatePresence>{editing && <EditModal lesson={editing} form={form} setForm={setForm} saving={saving} onClose={() => setEditing(null)} onSave={() => void save()} />}</AnimatePresence>
  </div>;
}
function LessonRow({ item, index, onEdit }: { item: service.AdminLesson; index: number; onEdit: () => void }) { const state = statusMeta[item.status || "draft"]; return <motion.tr initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .02 }} className="border-t border-border hover:bg-muted/30"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-muted text-xl">{item.emoji || "📘"}</span><span className="min-w-0"><strong className="block max-w-[300px] truncate">{item.title}</strong><small className="text-muted-foreground">Bài {item.lessonNumber}</small></span></div></td><td className="px-4 py-4"><strong className="block text-xs">{item.topicName}</strong><small className="text-muted-foreground">Chủ đề {item.topicNumber}</small></td><td className="px-4 py-4 text-xs text-muted-foreground">{item.gameType || "Chưa phân loại"}</td><td className="px-4 py-4 text-center"><span className="rounded-full bg-indigo-500/10 px-2.5 py-1 text-xs font-bold text-indigo-500">{item.requiredPlan}</span></td><td className="px-4 py-4 text-center"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${state.style}`}>{state.label}</span></td><td className="px-5 py-4 text-right"><button onClick={onEdit} className="inline-flex h-9 items-center gap-1.5 rounded-xl bg-indigo-500/10 px-3 text-xs font-bold text-indigo-500 transition hover:bg-indigo-500 hover:text-white"><Edit3 className="h-3.5 w-3.5" />Chỉnh sửa</button></td></motion.tr>; }
function EditModal({ lesson, form, setForm, saving, onClose, onSave }: { lesson: service.AdminLesson; form: Partial<service.AdminLesson>; setForm: (value: Partial<service.AdminLesson>) => void; saving: boolean; onClose: () => void; onSave: () => void }) { return <motion.div className="fixed inset-0 z-[100] grid place-items-center p-4" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><button aria-label="Đóng" className="absolute inset-0 bg-slate-950/65 backdrop-blur-sm" onClick={onClose} /><motion.div initial={{ scale: .96, y: 16 }} animate={{ scale: 1, y: 0 }} exit={{ scale: .96, y: 16 }} className="relative max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-[26px] border border-border bg-background p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wide text-indigo-500">Bài {lesson.lessonNumber} · Chủ đề {lesson.topicNumber}</p><h3 className="mt-1 text-xl font-extrabold">Chỉnh sửa bài học</h3></div><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-xl border border-border hover:bg-muted"><X className="h-4 w-4" /></button></div><div className="mt-6 space-y-4"><Field label="Tên bài học"><input value={form.title || ""} onChange={(e) => setForm({ ...form, title: e.target.value })} className="admin-field" /></Field><Field label="Mô tả"><textarea rows={3} value={form.description || ""} onChange={(e) => setForm({ ...form, description: e.target.value })} className="admin-field resize-none" /></Field><div className="grid grid-cols-2 gap-3"><Field label="Gói yêu cầu"><select value={form.requiredPlan || "FREE"} onChange={(e) => setForm({ ...form, requiredPlan: e.target.value as Plan })} className="admin-field"><option>FREE</option><option>PRO</option><option>VIP</option></select></Field><Field label="Trạng thái"><select value={form.status || "draft"} onChange={(e) => setForm({ ...form, status: e.target.value as Status })} className="admin-field"><option value="draft">Chưa hoàn thiện</option><option value="published">Đã hoàn thành</option></select></Field></div><div className="grid grid-cols-2 gap-3"><Field label="Loại nội dung"><input value={form.gameType || ""} onChange={(e) => setForm({ ...form, gameType: e.target.value })} className="admin-field" /></Field><Field label="Emoji"><input value={form.emoji || ""} onChange={(e) => setForm({ ...form, emoji: e.target.value })} className="admin-field" /></Field></div></div><div className="mt-7 flex justify-end gap-2"><button onClick={onClose} className="h-10 rounded-xl bg-muted px-4 text-sm font-bold">Hủy</button><button disabled={saving} onClick={onSave} className="inline-flex h-10 items-center gap-2 rounded-xl bg-indigo-500 px-4 text-sm font-bold text-white hover:bg-indigo-600"><Save className="h-4 w-4" />{saving ? "Đang lưu…" : "Lưu thay đổi"}</button></div></motion.div></motion.div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-xs font-bold text-muted-foreground">{label}</span>{children}</label>; }
